### ISSUE TITLE
[Question] Dumping code

### ISSUE THREAD

**Issue by AlterB** [myrdyr/ctf-writeups#1]
Hey guys, thanks for sharing these solutions.
Could you provide the steps to dump the code of converter.exe and Crypto.dll?
Did you use only Volatility?

Thanks again!

**Comment by myrdyr** [comment]
Unfortunately I do not remember how this was done. Either by the `dumpfile` option, using -Q with a physical address (there could be multiple for the same file, found by `filescan`) or through manual carving of the binary from memory.
